{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    name: {{ template "common.names.fullname" . }}
  annotations:
    pv.beta.kubernetes.io/gid: "100"   
spec:
  storageClassName: "{{ .Values.persistence.storageClass }}"
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  nfs:
    path: "/home/nfsshare/mongodb"
    server: 10.250.4.196
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
